/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3abcbd98-4767-4985-8077-b95576bef5ab",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_oofbobKJU",
    "aws_user_pools_web_client_id": "7ajina3uavs6d4ok06b75b6jk4",
    "oauth": {}
};


export default awsmobile;
